BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sophgo-sdk"
BBFILE_PATTERN_sophgo-sdk = "^${LAYERDIR}/"
BBFILE_PRIORITY_sophgo-sdk = "7"

LAYERDEPENDS_sophgo-sdk = "core sophgo"
LAYERSERIES_COMPAT_sophgo-sdk = "scarthgap"
