BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sophgo"
BBFILE_PATTERN_sophgo = "^${LAYERDIR}/"
BBFILE_PRIORITY_sophgo = "6"

LAYERDEPENDS_sophgo = "core"
LAYERSERIES_COMPAT_sophgo = "scarthgap"
