BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nanokvm"
BBFILE_PATTERN_nanokvm = "^${LAYERDIR}/"
BBFILE_PRIORITY_nanokvm = "8"

LAYERDEPENDS_nanokvm = "core sophgo sophgo-sdk"
LAYERSERIES_COMPAT_nanokvm = "scarthgap"
