BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nanokvm"
BBFILE_PATTERN_nanokvm = "^${LAYERDIR}/"
BBFILE_PRIORITY_nanokvm = "8"

# networking-layer: nftables/wireguard-tools; openembedded-layer: jansson
# (nftables runtime dep).
LAYERDEPENDS_nanokvm = "core sophgo networking-layer openembedded-layer"
LAYERSERIES_COMPAT_nanokvm = "scarthgap"
